MUTUAL-DE-SERVICIOS-AL-POLICIA/Arriendos-Backend

Arriendos_Backend/urls.py
login/urls.py
login/views.py
requirements.txt

Conexión con LDAP

---

login/urls.py
login/views.py

Validación de credenciales de los usuarios con LDAP closes #3

validación de usuarios en el servidor LDAP issue #3

---

login/views.py
users/urls.py
users/views.py

API para buscar usuarios en LDAP closes #7

Api para buscar usuario en Ldap issue #7

---

customers/admin.py
customers/apps.py
customers/models.py
customers/tests.py
customers/views.py

creacion de la aplicacion customers

---

Arriendos_Backend/urls.py
customers/serializer.py
customers/urls.py
customers/views.py

CRUD de customers y customer types closes #21

CRUD de Customers y validaciones

---

plans/admin.py
plans/apps.py
plans/models.py
plans/tests.py
plans/views.py

Creación de la aplicación Plans closes #23

Creación de la aplicacion Plans

---

customers/views.py
login/views.py
users/views.py

Validaciones de Ldap para registro de usuarios y API

Validaciones de Ldap y de API

---

plans/views.py
requirements/serializer.py

API  de planes y requisitos POST Y GET closes #43

API planes y requisitos

---

Arriendos_Backend/urls.py
products/serializers.py
products/views.py
requirements/serializer.py
requirements/urls.py
requirements/views.py

Api de los modelos Customers, Requirements, Rates y las rutas de requirements closes #55 closes #54

Api de Customers, Requirements y Rates

---

products/views.py
requirements/serializer.py
requirements/views.py

API de Requirement, Customer, Rates con paginación y post de Rates

API requisitos y tarifas con paginación

---

plans/views.py
requirements/serializer.py
requirements/urls.py
requirements/views.py

API Requirements, Rates, Customers con order by y serializers closes #68

API requisitos y clientes order by

---

login/views.py
users/serializers.py
users/urls.py
users/views.py

API de usuarios para activación y paginación de usuarios closes #72

API  usuarios de activación y paginación de usuarios

---

leases/models.py
leases/serializer.py
leases/urls.py
leases/views.py

APIs Get de fechas de arriendos y Post de arriendos closes #98

APIs Leases get y post

---

leases/views.py

Reestructuración de peticiones get y post de Leases closes #103

Reestructuración de APIs de arriendos

---

customers/urls.py
customers/views.py

API para edición de customers y contacts closes #109

API para edicion de customer y contacts

---

leases/views.py

Reestructuración de API leases con event_type closes #111

API Leases post reestructuración  event_type

---

products/migrations/0001_initial.py

Migración de products y hour range closes #108

Migración products con rango de horas

---

leases/models.py
leases/serializer.py
leases/views.py

APIs Leases con fechas y Ambientes closes #119

APIs Leases con Rooms y fechas

---

leases/serializer.py
leases/urls.py
leases/views.py

API Leases selected products con precios y total inicial closes #138 closes #135 closes #129

API Selected products con precios y total inicial

---

plans/serializer.py
plans/urls.py
plans/views.py

Refactorización API Plans Closes #140

Refactorización de API Plans

---

products/views.py

Adición de precio a API de posible products closes #148

Adición de precio a posible productos

---

leases/serializer.py
leases/views.py

API Rental edición de fechas closes #171

API Rental edición de fechas de los eventos y validación de fechas

---

requirements.txt
requirements/function.py
requirements/serializer.py
requirements/templates/reserva.html
requirements/views.py

Generación de formulario de reserva con requisitos entregados closes #173

Requisitos entregados y generación de Formulario de reserva

---

leases/views.py
requirements/views.py

Validación de requisitos entregados por arrendamientos closes #175

Validaciónes de requisitos entregados

---

financials/serializer.py
financials/urls.py
financials/views.py

API para registrar montos de ingreso de garantías closes #177

API para registrar montos de ingreso de garantías

---

financials/views.py

Adición de campo voucher en la API para registrar montos de ingreso

---

financials/serializer.py
financials/urls.py
financials/views.py

API para registrar descuentos por daños de evento de la Garantía

---

financials/urls.py
financials/views.py

API para registrar la devolución de la garantía

---

financials/function.py
financials/templates/ejecución_de_garantía.html
financials/views.py

Formulario de ejecución de la garantía close #193

Formulario de ejecución de la garantía

---

financials/function.py
financials/templates/solicitud_devolucion_de_garantia.html
financials/urls.py
financials/views.py

Generación de formulario de solicitud de devolución de garantía closes #200

Formulario de solicitud de devolución de garantía

---

leases/function.py
leases/serializer.py
leases/templates/entrega_y_recepcion_de_ambientes.html
leases/urls.py
leases/views.py

Generación de formulario de entrega y recepción de ambientes close #206

Formulario de entrega y recepción de ambientes

---

financials/function.py
financials/templates/devolucion_de_garantia.html
financials/urls.py
financials/views.py

Generación de formulario de devolución de garantía closes #212

Formulario de conformidad para devolución de garantía

---

leases/function.py
leases/templates/horas_extra.html
leases/views.py

Generación de formulario de horas extra close #214

Formulario de horas extra

---

leases/templates/entrega_y_recepcion_de_ambientes.html

Adición de numero de sub ambientes al formulario de entrega y recepción de ambientes closes #219

Adición de numero de sub ambiente a formulario de entrega de ambientes

---

leases/templates/entrega_y_recepcion_de_ambientes.html
leases/views.py

Mostrar arriendos sin estado cancelado o anulado en API Calendar closes #226

Validación de sólo arriendos no cancelados

---

customers/views.py

Refactorización de edición de Customers closes #228

Edición de contactos en CRUD Customers

---

financials/function.py
requirements/templates/reserva.html
users/views.py

Asignación de ambientes y usuarios, corrección de formulario de solicitud de reserva y ejecución de garantía closes #238

Asignación de usuarios y ambientes corrección

---

customers/views.py
requirements/views.py

Búsqueda de clientes y mensaje de error de API customers closes #247

Búsqueda de clientes closes#247

---

Arriendos_Backend/urls.py
requirements.txt

Instalación de drf spectacular para las Api closes #251

Instalación de DRF Spectacular

---

Arriendos_Backend/urls.py
requirements.txt

Instalación de Swagger para documentación de APIs closes #253

Documentación de APIs con Swagger

---

customers/urls.py
customers/views.py

Adición de Swagge a la aplicación Customers closes #255

Adición de documentación Swagger a Customers

---

products/serializers.py
products/urls.py
products/views.py

Adición de Swagger a la aplicación Products closes #259

Adición de Swagger a la aplicación Products

---

rooms/views.py

Adición de Swagger a la aplicación Rooms closes #261

Adición de Swagger a Rooms

---

leases/serializer.py
products/serializers.py
requirements/views.py

Adición de Swagger a la aplicación Requirements closes #265

Adición de Swagger a Requirements

---

financials/views.py
leases/views.py

Adición de Swagger a la aplicación Swagger closes #269

Adición de Swagger a Leases

---

login/urls.py
login/views.py
users/views.py

Adición de Swagger a la aplicación Login y Users closes #275

Adición de Swagger a Login y Users

---

leases/function.py
leases/templates/horas_extra.html
requirements/templates/reserva.html

Adición de descripción al formulario de horas extra closes #277

Adición de descripción a formulario de horas extra

---

requirements.txt
users/apps.py
users/signals.py
users/views.py

Adición de Records al modelo User closes #285

Adición de Records a user

---

users/signals.py

Formato de Records User

---

users/signals.py

Adición de registro a detail en Record closes #290

Adición de registro a detail Record

---

requirements/apps.py
requirements/signals.py
requirements/views.py

Adición de Records a la aplicación Requirements closes #294

Adición de Records a Requirements

---

products/apps.py
products/signals.py
products/views.py

Adición de Records a la aplicación Products closes #299

Adición de Records a Products

---

products/signals.py
requirements/signals.py

Records a Products closes #300

Records a Products

---

plans/apps.py
plans/signals.py
plans/views.py

Adición de records a la aplicación Plans closes #306

Adición de records a Plans

---

financials/views.py

Validación de formulario de conformidad de devolución de garantía closes #308

Validación de formulario de devolución de garantía

---

initial_data/customer_type.py
initial_data/rates_data.py
initial_data/requirements_data.py

Carga de datos iniciales de Requirements, Rates, Customer type closes #310

Datos iniciales para carga de datos

---

financials/function.py
financials/templates/solicitud_devolucion_de_garantia.html
financials/views.py
leases/templates/entrega_y_recepcion_de_ambientes.html
requirements/views.py

Adición de department a formularios closes #319

Adición de department a formularios

---

initial_data/plans_data.py

Datos de carga inicial de Plans closes #325

Datos de carga inicial de Plans

---

financials/templates/devolucion_de_garantia.html
leases/templates/entrega_y_recepcion_de_ambientes.html
leases/templates/horas_extra.html
leases/views.py

Adición de sub rooms a formularios closes #331

Adición de sub ambientes a formularios

---

initial_data/load_data.py
initial_data/sub_room_data.py

Datos de carga de sub ambientes closes #333

Datos de carga de sub room

---

customers/views.py
initial_data/load_data.py

Corrección de carga de datos de sub ambientes en initial data closes #352

Correción de carga de datos de sub ambientes

---

leases/function.py
leases/serializer.py
leases/urls.py
leases/views.py
requirements.txt

Creación de reporte por rango de fechas y estado closes #357

Creación de reporte por rango de fechas y estado

---

customers/views.py
requirements/views.py

Busqueda de customer type y requirements closes #362

Adición de busqueda de Customer type

---

financials/function.py
financials/templates/devolucion_de_garantia.html
financials/templates/ejecucion_de_garantia.html
leases/function.py
leases/templates/entrega_y_recepcion_de_ambientes.html
leases/templates/horas_extra.html
requirements/function.py
requirements/templates/reserva.html

Adición del NUP  a formularios closes #365

Adición del nup a formularios

---

leases/function.py
leases/views.py

Generación de formularios de entrega y recepción de ambientes y formulario de horas extra closes #389

Generación de formularios y reporte

---

financials/templates/devolucion_de_garantia.html
financials/templates/ejecucion_de_garantia.html
financials/templates/solicitud_devolucion_de_garantia.html

Adición de formato a formulario de solicitud de devolución de garantía, formulario de ejecución de la garantía y formulario de conformidad de la devolución de la garantía closes #391

Adición de formato a formularios de financials

---

financials/views.py
leases/templates/horas_extra.html

Adición de fecha a retorno de garantía y validación de evento sin horas extra en formulario de horas extra closes #397

Adición de fecha a retorno de garantía

---

financials/views.py
leases/templates/entrega_y_recepcion_de_ambientes.html

Validación de generación de formularios de la aplicación financials y corrección de formulario de entrega y recepción de ambientes closes #400

Validación de generación de formularios de aplicación financials

---

financials/views.py

Adición de fecha al retorno de la garantía closes #404

Adición de fecha para retorno de la garantía

---

financials/templates/devolucion_de_garantia.html
financials/templates/ejecucion_de_garantia.html
financials/templates/solicitud_devolucion_de_garantia.html
financials/views.py
leases/templates/entrega_y_recepcion_de_ambientes.html
leases/templates/horas_extra.html
leases/views.py
requirements/templates/reserva.html

Corrección de header de los formularios closes #408

Corrección de header de los formularios

---

requirements/function.py

Corrección de function de requirements closes #408

Corrección function de requirements

---

leases/views.py

Corrección de formulario de horas extra closes #389

Corrección de formulario de horas extra

---

financials/function.py
leases/function.py
leases/templates/horas_extra.html

Corrección de formato de fechas en reporte y formulario de horas extra closes #416

Correción de formato de fechas en reporte
